# Generated by Django 3.2.3 on 2024-03-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='ClubType',
        ),
    ]
