# Generated by Django 3.2.3 on 2024-03-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='name',
            new_name='club_name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='owner',
            new_name='club_owner',
        ),
    ]
